 docker compose up -d

docker compose build pyspark-batch

docker compose run --rm pyspark-batch
#to connect to timescaledb locally
 docker exec -it timescaledb psql -U transit_user -d transit_delays

docker compose down